### ISSUE TITLE
Implementing undo

### ISSUE THREAD

**Issue by kanyadirichard** [kanyadirichard/TODO_list-Richard_Kanyadi-CDOF2#1]
If the user marks a task completed but wants to reverse it they should be able to do it. For this purpose after the user submitted the index of the completed task there should be a request to confirm the intention. If the user wishes to undo the completion they choose the undo option and the task gets reverted to it's original state.

**Comment by tasi-zsombor** [comment]
I have already done it differently. I added an extra option, undo.
